package com.mp.challenge.components.dtos;

import jakarta.validation.constraints.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.util.List;

/**
 * CreateItemDto
 * <p>
 * Data Transfer Object for creating new items. This DTO is used specifically for
 * item creation operations where ID and timestamps are not required as they are
 * automatically generated by the system.
 * <p>
 * Features:
 * <ul>
 *   <li>Validation annotations for all required fields</li>
 *   <li>Builder pattern for flexible object creation</li>
 *   <li>No ID field (auto-generated)</li>
 *   <li>No timestamp fields (auto-generated)</li>
 *   <li>Optional fields marked appropriately</li>
 * </ul>
 * <p>
 * This component was built following my personal development standards.
 * The code presented here is protected by intellectual property laws and copyrights.
 *
 * @author Jose Quiroga
 * @since 15/10/2025
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CreateItemDto {
    
    @NotBlank(message = "Name is required and cannot be empty")
    @Size(min = 2, max = 100, message = "Name must be between 2 and 100 characters")
    private String name;

    @NotBlank(message = "Image URL is required")
    @Pattern(regexp = "https?://.+", message = "Image URL must be a valid HTTP or HTTPS URL")
    private String imageUrl;

    @Size(max = 500, message = "Description cannot exceed 500 characters")
    private String description;

    @NotNull(message = "Price is required")
    @DecimalMin(value = "0.01", message = "Price must be greater than 0")
    @Digits(integer = 10, fraction = 2, message = "Price must have at most 10 integer digits and 2 decimal places")
    private BigDecimal price;

    @DecimalMin(value = "0.0", message = "Rating must be at least 0")
    @DecimalMax(value = "5.0", message = "Rating must be at most 5")
    @Digits(integer = 1, fraction = 2, message = "Rating must have at most 1 integer digit and 2 decimal places")
    private BigDecimal rating;

    @Size(max = 20, message = "Cannot have more than 20 specifications")
    private List<@NotBlank(message = "Specification cannot be blank") @Size(max = 100, message = "Specification cannot exceed 100 characters") String> specifications;
}
